from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional, Dict
import os

app = FastAPI()

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # For development only
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Mount static files
app.mount("/static", StaticFiles(directory="frontend/static"), name="static")

# Templates
templates = Jinja2Templates(directory="frontend/templates")

# Sample data - Replace with your database
subjects_data = {
    "science": {
        "id": "science",
        "name": "Science",
        "grade": "Class 10",
        "chapters": [
            {
                "id": "ch1",
                "title": "Chemical Reactions",
                "description": "Learn about different types of chemical reactions",
                "topics": [
                    {
                        "id": "topic1",
                        "title": "Introduction to Chemical Reactions",
                        "content": "A chemical reaction is a process that leads to the chemical transformation of one set of chemical substances to another."
                    },
                    {
                        "id": "topic2",
                        "title": "Types of Chemical Reactions",
                        "content": "Chemical reactions can be classified into several types including combination, decomposition, displacement, and double displacement."
                    }
                ]
            }
        ]
    },
    "social": {
        "id": "social",
        "name": "Social Science",
        "grade": "Class 10",
        "chapters": [
            {
                "id": "ch2",
                "title": "Indian National Movement",
                "description": "Study the history of Indian independence movement",
                "topics": [
                    {
                        "id": "topic3",
                        "title": "Early Nationalist Movements",
                        "content": "The early nationalist movements in India laid the foundation for the independence struggle."
                    }
                ]
            }
        ]
    }
}

# Pydantic models
class Question(BaseModel):
    question: str
    context: Optional[Dict] = None

class Answer(BaseModel):
    answer: str
    sources: List[str] = []

# Frontend routes
@app.get("/", response_class=HTMLResponse)
async def read_root(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})

@app.get("/chapter/{chapter_id}", response_class=HTMLResponse)
async def read_chapter(request: Request, chapter_id: str):
    return templates.TemplateResponse("chapter.html", {"request": request, "chapter_id": chapter_id})

# API routes
@app.get("/api/subjects")
async def get_subjects():
    return [
        {"id": subject_id, "name": data["name"], "grade": data["grade"]}
        for subject_id, data in subjects_data.items()
    ]

@app.get("/api/chapters/{subject_id}")
async def get_chapters(subject_id: str):
    if subject_id not in subjects_data:
        raise HTTPException(status_code=404, detail="Subject not found")
    return subjects_data[subject_id]["chapters"]

@app.get("/api/chapter/{chapter_id}")
async def get_chapter(chapter_id: str):
    for subject in subjects_data.values():
        for chapter in subject["chapters"]:
            if chapter["id"] == chapter_id:
                return chapter
    raise HTTPException(status_code=404, detail="Chapter not found")

@app.get("/api/topic/{topic_id}")
async def get_topic(topic_id: str):
    for subject in subjects_data.values():
        for chapter in subject["chapters"]:
            for topic in chapter["topics"]:
                if topic["id"] == topic_id:
                    return topic
    raise HTTPException(status_code=404, detail="Topic not found")

@app.post("/api/tutor/ask")
async def ask_question(question: Question):
    # This is where you'd integrate your AI model
    # For now, return a sample response
    return Answer(
        answer="This is a sample answer to your question. In a real implementation, this would be generated by an AI model.",
        sources=["Sample Source 1", "Sample Source 2"]
    )

# File structure setup
def setup_file_structure():
    """Create necessary directories if they don't exist"""
    directories = [
        "frontend/static/css",
        "frontend/static/js",
        "frontend/static/img",
        "frontend/templates"
    ]
    
    for directory in directories:
        os.makedirs(directory, exist_ok=True)

